language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer selfupdate
  - composer install
  - phpenv rehash

script:
  - php vendor/bin/phpcs --standard=psr2 src/
  - phpunit --coverage-text
